version: '3.8'

services:
  # sync-server:
  #   image: ghcr.io/automerge/automerge-repo-sync-server:main
  #   container_name: autoblog-sync-server
  #   ports:
  #     - "3030:3030"
  #   restart: unless-stopped
  #   networks:
  #     - autoblog-network

  autoblog-web:
    image: evcraddock/autoblog-web:1.0.4
    container_name: autoblog-web
    ports:
      - "8085:80"
    environment:
      - REACT_AUTOBLOG_SYNC_URL=${AUTOBLOG_SYNC_URL}
      - REACT_AUTOBLOG_INDEX_ID=${AUTOBLOG_INDEX_ID}
    # depends_on:
    #   - sync-server
    restart: unless-stopped
    networks:
      - autoblog-network

networks:
  autoblog-network:
    driver: bridge