version: '3.8'

services:
  autoblog-web:
    image: evcraddock/autoblog-web:1.0.2
    container_name: autoblog-web
    ports:
      - "8085:80"
    environment:
      - APP_AUTOBLOG_SYNC_URL=${APP_AUTOBLOG_SYNC_URL:-wss://sync.automerge.org}
      - APP_AUTOBLOG_INDEX_ID=${APP_AUTOBLOG_INDEX_ID}
    restart: unless-stopped
    networks:
      - autoblog-network

networks:
  autoblog-network:
    driver: bridge