name: Deploy Website

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'autoblog-web/**'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current version
        id: version
        run: |
          cd autoblog-web
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Calculate next patch version
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="$MAJOR.$MINOR.$NEXT_PATCH"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in package.json
        run: |
          cd autoblog-web
          npm version ${{ steps.version.outputs.next_version }} --no-git-tag-version
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./autoblog-web
          file: ./autoblog-web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/autoblog-web:latest
            ${{ secrets.DOCKER_USERNAME }}/autoblog-web:${{ steps.version.outputs.next_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Commit version update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd autoblog-web
          git add package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.next_version }}"
          git push