name: Web Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'autoblog-web/**'
      - '.github/workflows/web-quality.yml'

jobs:
  bundle-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: autoblog-web/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: autoblog-web
      
    - name: Build application
      run: npm run build
      working-directory: autoblog-web
      
    - name: Analyze bundle size
      run: |
        echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo "| File | Size | Gzipped |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|---------|" >> $GITHUB_STEP_SUMMARY
        
        # Find all JS and CSS files in dist
        for file in $(find autoblog-web/dist -name "*.js" -o -name "*.css" | sort); do
          size=$(du -h "$file" | cut -f1)
          gzipped=$(gzip -c "$file" | wc -c | awk '{print $1/1024 "KB"}')
          filename=$(basename "$file")
          echo "| $filename | $size | $gzipped |" >> $GITHUB_STEP_SUMMARY
        done
        
        # Total size
        total_size=$(du -sh autoblog-web/dist | cut -f1)
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Total build size:** $total_size" >> $GITHUB_STEP_SUMMARY
      
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: autoblog-web/package-lock.json
        
    - name: Run npm audit
      run: npm audit --production
      working-directory: autoblog-web
      continue-on-error: true
      
    - name: Check for outdated dependencies
      run: npm outdated || true
      working-directory: autoblog-web